### ISSUE TITLE
Logout error because of null item

### ISSUE THREAD

**Issue by Robertoq7** [saantiaguilera/android-api-RxFacebook#7]
Hi,

Congratulation man, great library, but I have an issue :( When I call the logout:
`RxFacebook.Companion.create() .logout()...`

then I got this:
>  java.lang.NullPointerException: The item is null
                                                               at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                               at io.reactivex.Observable.just(Observable.java:1973)
                                                               at com.u.rxfacebook.RxFacebook.logout(RxFacebook.kt:337)

You call this in RxFacebook.kt, line 337
`Observable.just<Void>(null)`

but the item can not be null in "io.reactivex.Observable.just(Observable.java:1973)"
`public static <T> Observable<T> just(T item) {
        ObjectHelper.requireNonNull(item, "The item is null");`

Can you fix it please? I'm using v2.0.0.

Thank you,
Robert

**Comment by saantiaguilera** [comment]
Fix can be found from version [2.0.1](https://github.com/saantiaguilera/android-api-RxFacebook/releases/tag/v2.0.1) onwards :)
